name: Tests
description: Run tests for a package
inputs:
  working-directory:
    description: the path to the directory from repository root
    type: string
    required: true
  test-type:
    # Can be one of:
    # eyes_images_functional_tests
    # eyes_playwright_functional_tests
    # eyes_playwright_generated_tests
    # eyes_robotframework_functional_tests
    # eyes_robotframework_sauce_functional_tests
    # eyes_selenium_functional_tests
    # eyes_selenium_generated_tests
    # eyes_selenium_installation_tests
    # eyes_selenium_sauce_functional_tests
    # unit_tests
    description: type of the testing
    type: string
  build-type:
    description: type of the build script
    type: string
  setup-type:
    description: type of the setup script
    type: string
  remote:
    description: remote type
    type: string
    default: local
  links:
    description: names of package directories to link before testing
    type: string
  grep:
    description: grep pattern to filter tests
    type: string
  jobs:
    description: number of jobs to run tests in parallel
    type: string
  report:
    description: report level
    type: string
    default: sandbox
  shell:
    description: shell to use
    type: string
    default: bash
runs:
  using: composite
  steps:
    - name: Test
      shell: ${{inputs.shell}}
      working-directory: ${{inputs.working-directory}}
      env:
        APPLITOOLS_TEST_REMOTE: ${{inputs.remote}}
        MOCHA_GREP: ${{inputs.grep}}
        MOCHA_JOBS: ${{inputs.jobs}}
      run: |
        echo "::group::Configure NPM and YARN"
        if [ "${{runner.os}}" = "Windows" ]; then npm config set script-shell "C:\\Program Files\\Git\\bin\\bash.exe"; fi
        yarn config set ignore-engines true
        echo "::endgroup::"

        echo "::group::Installing and updating dependencies"
        yarn install
        if [ "${{runner.os}}" = "Windows" ]
        then
          npm run deps --if-present --script-shell $COMSPEC
        else
          npm run deps --if-present
        fi
        npm run upgrade:framework --if-present
        echo "::endgroup::"

        if [ ! -z "${{inputs.links}}" ]
        then
          echo "::group::Linking dependencies"
          yarn --cwd ../scripts install
          yarn --cwd ../scripts link
          yarn link @applitools/scripts
          npx -p @applitools/scripts link "${{inputs.links}}" --build --install
          ls -F ./node_modules/@applitools
          echo "::endgroup::"
        fi

        echo "::group::Building package"
        if [ ! -z "${{inputs.build-type}}" ]
        then
          if [ "${{inputs.build-type}}" != "none" ]; then npm run build:${{inputs.build-type}}; fi
        else
          npm run build --if-present
        fi
        echo "::endgroup::"

        echo "::group::Setting up test environment"
        if [ ! -z "${{inputs.setup-type}}" ]
        then
          if [ "${{inputs.setup-type}}" != "none" ]; then npm run setup:${{inputs.setup-type}}; fi
        else
          npm run setup --if-present
        fi
        if [ -e .env ]
        then
          set -o allexport
          source .env
          set +o allexport
        fi
        echo "::endgroup::"

        echo "::group::Running tests"
        USDK_BUILD_DIR=`realpath bin`
        make --directory=${{github.workspace}}/python ${{inputs.test-type}}
        echo "::endgroup::"
