name: Tests
description: Run tests for a package
inputs:
  test-type:
    # Can be one of:
    # eyes_images_functional_tests
    # eyes_playwright_functional_tests
    # eyes_playwright_generated_tests
    # eyes_robotframework_functional_tests
    # eyes_robotframework_sauce_functional_tests
    # eyes_selenium_functional_tests
    # eyes_selenium_generated_tests
    # eyes_selenium_installation_tests
    # eyes_selenium_sauce_functional_tests
    # unit_tests
    required: true
    description: type of the testing
  pytest-filter:
    required: false
    description: grep pattern to filter tests
  core-build-dir:
    required: false
    description: path to core-universal binaries
  bongo-report:
    default: false
    description: send bongo report, without bongo-report-release-package it will be marked as sandbox
  bongo-report-release-package:
    required: false
    description: name of a package being released, bongo report will be marked as prod
runs:
  using: composite
  steps:
    - name: Test
      shell: bash
      env:
        BONGO_REPORT_TESTS: ${{inputs.bongo-report}}
        RELEASING_PACKAGE: ${{inputs.bongo-report-release-package}}
        PYTEST_FILTER: ${{inputs.pytest-filter}}
        USDK_BUILD_DIR: ${{inputs.core-build-dir}}
      run: |
        make --directory=${{github.workspace}}/python ${{inputs.test-type}}
