name: Publish

on:
  workflow_dispatch:
    inputs:
      packages:
        description: package names (aliases)
        required: true
      default-version:
        description: default version type
        type: choice
        options: [ patch, minor, major ]
        default: patch
      include-dependencies:
        description: include dependencies
        type: boolean
        default: true
      include-only-changed:
        description: include only packages with new commits
        type: boolean
        default: true

env:
  FORCE_COLOR: 3
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      packages: ${{steps.setup.outputs.packages}}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/parser
        id: setup
        with:
          packages: ${{github.event.inputs.packages}}
          include-only-changed: ${{github.event.inputs.include-only-changed}}
          include-dependencies: ${{github.event.inputs.include-dependencies}}
          default-publish-version: ${{github.event.inputs.default-version}}

  # INTERNAL
  utils:
    needs: [ setup ]
    if: ${{fromJSON(needs.setup.outputs.packages).utils && !failure() && !cancelled()}}
    name: utils
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-utils.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).utils.params.version}}"}'
  logger:
    needs: [ setup, utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).logger && !failure() && !cancelled()}}
    name: logger
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-logger.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).logger.params.version}}"}'
  socket:
    needs: [ setup, logger, utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).socket && !failure() && !cancelled()}}
    name: socket
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-socket.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).socket.params.version}}"}'
  req:
    needs: [ setup, utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).req && !failure() && !cancelled()}}
    name: req
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-req.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).req.params.version}}"}'
  snippets:
    needs: [ setup ]
    if: ${{fromJSON(needs.setup.outputs.packages).snippets && !failure() && !cancelled()}}
    name: snippets
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-snippets.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).snippets.params.version}}"}'
  image:
    needs: [ setup, utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).image && !failure() && !cancelled()}}
    name: image
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-image.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).image.params.version}}"}'
  screenshoter:
    needs:
      [
        setup,
        image,
        logger,
        snippets,
        utils,
        driver,
        spec-webdriverio,
        test-utils
      ]
    if: ${{fromJSON(needs.setup.outputs.packages).screenshoter && !failure() && !cancelled()}}
    name: screenshoter
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-screenshoter.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).screenshoter.params.version}}"}'
  driver:
    needs: [ setup, logger, snippets, utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).driver && !failure() && !cancelled()}}
    name: driver
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-driver.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).driver.params.version}}"}'

  # TESTING BASE
  test-utils:
    needs: [ setup ]
    if: ${{fromJSON(needs.setup.outputs.packages).test-utils && !failure() && !cancelled()}}
    name: test-utils
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-test-utils.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).test-utils.params.version}}"}'
  test-server:
    needs: [ setup, logger, utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).test-server && !failure() && !cancelled()}}
    name: test-server
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-test-server.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).test-server.params.version}}"}'

  # CORE
  core-base:
    needs:
      [
        setup,
        image,
        logger,
        req,
        utils,
        test-server,
        test-utils
      ]
    if: ${{fromJSON(needs.setup.outputs.packages).core-base && !failure() && !cancelled()}}
    name: core-base
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-core-base.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).core-base.params.version}}"}'
  core:
    needs:
      [
        setup,
        core-base,
        driver,
        ec-client,
        logger,
        nml-client,
        req,
        screenshoter,
        snippets,
        socket,
        spec-webdriver,
        ufg-client,
        utils,
        spec-puppeteer,
        spec-selenium,
        spec-webdriverio,
        test-server,
        test-utils
      ]
    if: ${{fromJSON(needs.setup.outputs.packages).core && !failure() && !cancelled()}}
    name: core
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-core.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).core.params.version}}"}'
  ufg-client:
    needs: [ setup, logger, req, utils, test-server, test-utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).ufg-client && !failure() && !cancelled()}}
    name: ufg-client
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-ufg-client.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).ufg-client.params.version}}"}'
  ec-client:
    needs:
      [
        setup,
        core-base,
        driver,
        logger,
        req,
        socket,
        spec-webdriver,
        utils,
        test-server
      ]
    if: ${{fromJSON(needs.setup.outputs.packages).ec-client && !failure() && !cancelled()}}
    name: ec-client
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-ec-client.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).ec-client.params.version}}"}'
  nml-client:
    needs:
      [
        setup,
        logger,
        req,
        utils,
        spec-webdriverio,
        test-server,
        test-utils
      ]
    if: ${{fromJSON(needs.setup.outputs.packages).nml-client && !failure() && !cancelled()}}
    name: nml-client
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-nml-client.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).nml-client.params.version}}"}'
  eyes:
    needs: [ setup, core, logger, utils, req ]
    if: ${{fromJSON(needs.setup.outputs.packages).eyes && !failure() && !cancelled()}}
    name: eyes
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-eyes.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).eyes.params.version}}"}'

  # SPEC DRIVERS
  spec-playwright:
    needs: [ setup, driver, utils, test-utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).spec-playwright && !failure() && !cancelled()}}
    name: spec-playwright
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-spec-playwright.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).spec-playwright.params.version}}"}'
  spec-puppeteer:
    needs: [ setup, driver, utils, test-utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).spec-puppeteer && !failure() && !cancelled()}}
    name: spec-puppeteer
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-spec-puppeteer.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).spec-puppeteer.params.version}}"}'
  spec-webdriver:
    needs: [ setup, driver, utils, test-server, test-utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).spec-webdriver && !failure() && !cancelled()}}
    name: spec-webdriver
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-spec-webdriver.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).spec-webdriver.params.version}}"}'
  spec-webdriverio:
    needs: [ setup, driver, utils, test-utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).spec-webdriverio && !failure() && !cancelled()}}
    name: spec-webdriverio
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-spec-webdriverio.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).spec-webdriverio.params.version}}"}'
  spec-selenium:
    needs: [ setup, driver, utils, test-utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).spec-selenium && !failure() && !cancelled()}}
    name: spec-selenium
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-spec-selenium.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).spec-selenium.params.version}}"}'

  # JS SDKS
  images:
    needs: [ setup, eyes, test-utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).images && !failure() && !cancelled()}}
    name: images
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-images.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).images.params.version}}"}'
  playwright:
    needs: [ setup, eyes, spec-playwright, test-utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).playwright && !failure() && !cancelled()}}
    name: playwright
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-playwright.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).playwright.params.version}}"}'
  puppeteer:
    needs: [ setup, eyes, spec-puppeteer, test-utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).puppeteer && !failure() && !cancelled()}}
    name: puppeteer
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-puppeteer.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).puppeteer.params.version}}"}'
  webdriverio:
    needs: [ setup, eyes, spec-webdriverio, test-utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).webdriverio && !failure() && !cancelled()}}
    name: webdriverio
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-webdriverio.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).webdriverio.params.version}}"}'
  selenium:
    needs: [ setup, eyes, spec-selenium, test-utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).selenium && !failure() && !cancelled()}}
    name: selenium
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-selenium.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).selenium.params.version}}"}'
  nightwatch:
    needs:
      [
        setup,
        driver,
        eyes,
        spec-webdriver,
        utils,
        test-utils
      ]
    if: ${{fromJSON(needs.setup.outputs.packages).nightwatch && !failure() && !cancelled()}}
    name: nightwatch
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-nightwatch.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).nightwatch.params.version}}"}'
  testcafe:
    needs: [ setup, core, utils, test-server, test-utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).testcafe && !failure() && !cancelled()}}
    name: testcafe
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-testcafe.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).testcafe.params.version}}"}'
  cypress:
    needs: [ setup, core, logger, utils, test-server, test-utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).cypress && !failure() && !cancelled()}}
    name: cypress
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-cypress.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).cypress.params.version}}"}'
  browser-extension:
    needs: [ setup, utils, spec-playwright, test-utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).browser-extension && !failure() && !cancelled()}}
    name: browser-extension
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-browser-extension.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).browser-extension.params.version}}"}'
  storybook:
    needs:
      [
        setup,
        core,
        driver,
        logger,
        spec-puppeteer,
        test-server,
        ufg-client,
        utils
      ]
    if: ${{fromJSON(needs.setup.outputs.packages).storybook && !failure() && !cancelled()}}
    name: storybook
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-storybook.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).storybook.params.version}}"}'
